services:
  - name: temu_twitter
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: twitter_clone_nwoi
          property: connectionString
      - key: SECRET_KEY
        sync: false  
databases:
  - name: twitter_clone_nwoi
    type: postgresql